### ISSUE TITLE
Tag and pypi release don't match

### ISSUE THREAD

**Issue by imphil** [henryiii/validate-pyproject-schema-store#8]
The latest tag is `2024.01.29`, but the [PyPi release](https://pypi.org/project/validate-pyproject-schema-store/#history) is named `2024.1.29` (note the missing `0`). Looks like something with the release scripts is wrong?

**Comment by henryiii** [comment]
PyPI releases (Python version numbers) do not contain leading 0's. `1.01.01` is `1.1.1`. The tag uses leading zeros to sort nicely, but the Python version number doesn't reflect that.

```pycon
>>> import packaging.version
>>> packaging.version.Version("1.01")
<Version('1.1')>
```

**Comment by imphil** [comment]
I see. Unfortunately, that's causing a bit of confusion, since pre-commit uses the git tag in some places, and in other places the PyPi version:

```
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.16
  hooks:
    - id: validate-pyproject
      additional_dependencies:
        - validate-pyproject[all]
        - validate-pyproject-schema-store==2024.1.29
```

vs.

```
- repo: https://github.com/henryiii/validate-pyproject-schema-store
  rev: "2024.01.29"
  hooks:
    - id: validate-pyproject
```

I haven't done further research on how other date-based projects solve this. Maybe giving up the sortability of the tags? If nothing else, a bit of documentation will help.

**Comment by henryiii** [comment]
```yaml
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.16
  hooks:
    - id: validate-pyproject
      additional_dependencies:
        - validate-pyproject[all]
        - validate-pyproject-schema-store==2024.01.29
```
Works, I think. You can always add leading zeros. I’ll check some other CalVer projects to see how they tag.
