### ISSUE TITLE
#88 broke `ruff==0.7` configs on `TCH` to `TC` rename

### ISSUE THREAD

**Issue by jamesbraza** [henryiii/validate-pyproject-schema-store#89]
https://github.com/henryiii/validate-pyproject-schema-store/pull/88 accommodated the Ruff rename from `TCH` to `TC`.

However, for people who haven't gone to `0.8` yet, it breaks `pre-commit`.

Can you bring back `TCH` settings with something like a `"deprecated": true`?

**Comment by henryiii** [comment]
I don’t think you can deprecate parts of an enum. And this is just a mirror of the contents of SchemaStore. Which itself is just a mirror of Ruff’s Schema output.

Can’t you pin on this repo in pre-commit And then update them together?

**Comment by jamesbraza** [comment]
> I don’t think you can deprecate parts of an enum.

Ah gotchu, yeah too bad.

> And this is just a mirror of the contents of SchemaStore. Which itself is just a mirror of Ruff’s Schema output.

> Can’t you pin on this repo in pre-commit And then update them together?

I think it makes sense for SchemaStore to be latest release focused. I guess `validate-pyproject-schema-store` sort of "connects the dots" here, as it's the vehicle to deploy schemae from SchemaStore to `pre-commit`, so maybe it shouldn't be so latest-focused. Food for thought, not sure there's a real solution here.

I guess this week my `pre-commit` config was unchanged (neither `ruff` nor `validate-pyproject-schema-store`), and suddenly `pre-commit` CI goes down due to `TCH` --> `TC`. I am trying to think of how to avoid `validate-pyproject-schema-store` periodically breaking me and forcing synchronization with latest Ruff.

---

Anyways, I realize that for now the best solution is to upper bound or exactly pin `validate-pyproject-schema-store`, which I will do.

Thanks again and appreciate your help and for making this tool as always! 👍

**Comment by henryiii** [comment]
Using:

```YAML
repos:
  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: <insert here>
    hooks:
      - id: validate-pyproject
```

will control updates to this and should stay in sync with updates to Ruff if you update together.

**Comment by jamesbraza** [comment]
Ooo I like what you're thinking. What I previously had was:

```yaml
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject
        additional_dependencies:
          - "validate-pyproject-schema-store[all]>=2024.06.24"
```

Which will install `validate-pyproject[all] validate-pyproject-schema-store[all]>=2024.06.24`.

Going to what you've suggested seems to install `validate-pyproject[all]`. Would it still include `validate-pyproject-schema-store`?

**Comment by henryiii** [comment]
Yes, that's the repo you are using (and pinning). It won't pin validate-pyproject, but as you've seen, pinning the schemas is likely more important.

```yaml
repos:
  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: 2024.06.24
    hooks:
      - id: validate-pyproject
```

for example.
